defaults:

  - model: mlm

seed: ${trial_id}
trial_id: 0
project_name: guided_seq
data_dir: /your_folder/your_data


train_fn: train_data.csv 
val_fn: val_data.csv



max_samples: 10000
target_cols: null



discr_batch_ratio: null
vocab_file: /your_folder/your_vocab
vocab_size: 10

use_alignment_tokens: False


log_dir: /your_folder/your_configs

exp_name: ar_mlm_test
exp_dir: ${log_dir}/${exp_name}

val_sample_frequency: 4
num_samples: 256
infill_seeds_fn: null 

resume_ckpt: null

max_seq_len: 80
min_seq_len: 80

trim_strategy: "randomcrop"
gradient_clip: 10.0
min_epochs: 100
max_epochs: 100
early_stop_patience: 0

batch_size: 128

loader_workers: 8


ngpu: 1

hydra:
  run:
    dir: ${log_dir}
  sweep:
    dir: ${log_dir}
